Exportable Section
eielelle/gradify-web pull request #28
Opened 2024-07-24 15:02 UTC by Jmsmr

2024-07-26 22:39 UTC, eielelle requested changes
run rubocop

2024-07-26 22:39 UTC, eielelle commented on app/controllers/admin/sections_controller.rb
run rubocop

2024-07-29 20:32 UTC, eielelle requested changes

2024-07-29 20:32 UTC, eielelle commented on app/controllers/concerns/section_searchable.rb
use searchable concern instead of creating new one

2024-08-06 05:39 UTC, eielelle commented
run rubocop

2024-08-07 13:25 UTC, Jmsmr commented
> run rubocop
the error here still the bundle 
![image](https://github.com/user-attachments/assets/826face8-aa19-4ca6-90a9-9eaa87dcd26e)

2024-08-07 15:08 UTC, merged